package com.example.pc.updata.bmob;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.pc.updata.bmob.NoteFrament2;

import com.example.pc.updata.bmob.NoteFrament2Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig noteFrament2DaoConfig;

    private final NoteFrament2Dao noteFrament2Dao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        noteFrament2DaoConfig = daoConfigMap.get(NoteFrament2Dao.class).clone();
        noteFrament2DaoConfig.initIdentityScope(type);

        noteFrament2Dao = new NoteFrament2Dao(noteFrament2DaoConfig, this);

        registerDao(NoteFrament2.class, noteFrament2Dao);
    }
    
    public void clear() {
        noteFrament2DaoConfig.clearIdentityScope();
    }

    public NoteFrament2Dao getNoteFrament2Dao() {
        return noteFrament2Dao;
    }

}
